version: "3"

services:

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - /var/lib/rabbitmq
    env_file:
      - ./env/rabbitmq.env
    hostname: rabbitmq

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    env_file:
      - ./env/postgres.env


  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./configs/prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - localprom

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter
    ports:
      - "9100:9100"
    networks:
      - localprom

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    env_file:
      - ./env/grafana.env
    depends_on:
      - prometheus

networks:
  localprom:
    driver: bridge
