version: '3.9'

services:

  users-service:
    container_name: users_api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3001:3001"
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - users_network

  users-postgres:
    container_name: users_postgres
    image: postgres
    restart: always
    ports:
      - "5001:5001"
    expose:
      - "5001"
    env_file:
      - env/postgres.env
    volumes:
      - ./db-data/postgres:/var/lib/postgresql/data
    networks:
      - users_network

volumes:
  db-data:

networks:
  users_network: