version: '3.9'

services:

  logger-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1

  mongo:
    image: 'mongo:4.2.16-bionic'
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: logs
      MONGO_INITDB_USERNAME: admin
      MONGO_INITDB_PASSWORD: password
    volumes:
      - ./db-data/mongo/:/data/db