import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/ThemeProvider'
import { ReactNode } from 'react'
import { cookies } from 'next/headers'
import NextAuthProvider from '@/lib/auth/Provider'
import TrpcProvider from '@/lib/trpc/Provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <NextAuthProvider>
            <TrpcProvider cookies={cookies().toString()}>
              {children}
            </TrpcProvider>
          </NextAuthProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
