version: '3.9'

services:

  portal-service:
    container_name: portal_api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3003:3003"
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - users_network

  portal-postgres:
    container_name: portal_postgres
    image: postgres
    restart: always
    ports:
      - "5003:5003"
    expose:
      - "5003"
    env_file:
      - env/postgres.env
    volumes:
      - ./db-data/postgres:/var/lib/postgresql/data
    networks:
      - users_network

volumes:
  db-data:

networks:
  users_network: